### ISSUE TITLE
Cannot read property 'headers' of undefined at Assertion.<anonymous>

### ISSUE THREAD

**Issue by cmattern68** [chaijs/chai-http#276]
I get this error when I'm running my unit tests on gitlab pipeline, but it work fine on my local environement:

```js
TypeError: Cannot read property 'headers' of undefined
    at Assertion.<anonymous> (node_modules/chai-http/lib/http.js:175:19)
    at Assertion.propertyGetter (node_modules/chai/lib/chai/utils/addProperty.js:62:29)
    at Object.get (<anonymous>)
    at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:98:22)
    at Assertion.<anonymous> (node_modules/chai-http/lib/http.js:224:40)
    at Assertion.propertyGetter (node_modules/chai/lib/chai/utils/addProperty.js:62:29)
    at Object.get (<anonymous>)
    at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:98:22)
    at /app/tests/Auth/AuthGetRegister.js:10:21
    at Test.Request.callback (node_modules/superagent/lib/node/index.js:728:3)
    at ClientRequest.<anonymous> (node_modules/superagent/lib/node/index.js:647:10)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
Here is my unit tests files architecture:

```
tests/
├── Auth/
│   ├── AuthGetRegister.js
├── common.js
└── top.js
```

The app is also working on docker environment.

Unit tests are run by the following command:
```bash
./node_modules/.bin/mocha tests --reporter mocha-junit-reporter --reporter-options mochaFile=./test_results/test-results.xml --unhandled-rejections=strict
```

common.js:
```js
let chai = require("chai");
let chaiHttp = require('chai-http');
let jwt = require('jsonwebtoken');
let fs = require('fs');

let privateKey = fs.readFileSync( __dirname + '/../RSA/jwtRS256.key');
let options = {
	server: "http://localhost:3000/api",
	jwt: jwt.sign({ userId: "fa76aff7-83e7-4ec2-b3e7-79d1629577b0" }, privateKey, { expiresIn: '3m',  algorithm: 'RS256' })
};

chai.use(chaiHttp);

exports.options = options;
exports.chai = chai;
exports.assert = chai.assert;
exports.expect = chai.expect;
```

top.js:
```js
var common = require("./common");

/*
**	Auth
*/

describe("GET /api/auth/register", function () {
	require('./Auth/AuthGetRegister');
});
```

AuthGetRegister.js:
```js
let common = require("../common");
let options = common.options;
let chai = common.chai;
let expect = common.expect;

it('it should return status 200 with a list of pathologies', (done) => {
	chai.request(options.server)
		.get('/auth/register')
		.end((err, res) => {
			expect(res).to.be.json;
			expect(res).to.have.status(200);
			done();
		});
});
```

I put AuthGetRegister as exemple, but get the same error for all my unit tests.

I already tried the workarounds proposed [here][1], but it dosent work.

Thanks for your help !

  [1]: https://github.com/chaijs/chai-http/issues/150

**Comment by austince** [comment]
Hey, not sure if this is the issue (and if so, bad error message), but can you confirm that you actually have a server running at `http://localhost:3000`? Chai-http will not spin up a server for you when just given the endpoint.

**Comment by cmattern68** [comment]
Hey, yes, I confirm that my server is runing on 3000

```log
[nodemon] starting `node ./server.js`
Listening on port 3000
```

**Comment by austince** [comment]
And you can send a `GET` request to `/api/auth/register` outside of your test case?

**Comment by cmattern68** [comment]
Outside the test case, here is an exemple of the response from this route:
```json
{
    "data": {
        "pathologies": [
            {
                "id": "c3923282-74ec-4976-8ae9-5acbec5fbeda",
                "name": "Polyarthrite Rhumatoïde"
            },
        ],
        "articulations": [
            {
                "id": "91d8481c-c261-4ecc-9f46-d013f02211ff",
                "label": "Cou",
                "part": "neck"
            },
        ]
    }
}
```

When i'm running the test command on my computer, the xml file is well generated by junit-reporter (as you can see below)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.4620" tests="18" failures="0">
  <testsuite name="Root Suite" timestamp="2020-10-05T13:19:39" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="GET /api/auth/register" timestamp="2020-10-05T13:19:39" tests="1" file="/app/tests/top.js" time="0.1030" failures="0">
    <testcase name="GET /api/auth/register it should return status 200 with a list of pathology" time="0.1030" classname="it should return status 200 with a list of pathology">
    </testcase>
  </testsuite>
</testsuites>
```

But when the command is run by Gitlab pipeline, the error occurs. I can also confirm that the test command is run after checking if the node server is running.

**Comment by austince** [comment]
So this test passes locally for you?

**Comment by cmattern68** [comment]
Yes, it pass locally, but not on the pipeline.

**Comment by austince** [comment]
Ah missed that from the description, sorry. Can you share your gitlab pipeline, since that seems to be what's actually the issue?

**Comment by cmattern68** [comment]
No worries ! Yep, here it is:

Pipeline configuration:
```yml
image:
  name: docker/compose:1.24.0
  entrypoint: ["/bin/sh", "-c"]


variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:18.09.7-dind

build:
  stage: build
  script:
    - docker-compose build
  only:
    - develop
    - merge_requests

test:
  stage: test
  before_script:
    - docker-compose build
    - docker-compose up -d
  script:
    - docker-compose exec -T app sequelize db:migrate
    - docker-compose exec -T app sequelize db:seed:all
    - docker-compose exec -T app npm test
  after_script:
    - docker-compose stop
  artifacts:
    when: always
    paths:
      - test_results/test-results.xml
    reports:
      junit: test_results/test-results.xml
```

Log:
```log
$ docker-compose up -d
Creating network "rhumapp_default" with the default driver
Creating volume "rhumapp_postgres" with default driver
Creating volume "rhumapp_pgadmin" with default driver
Pulling postgres (postgres:alpine)...
alpine: Pulling from library/postgres
Status: Downloaded newer image for postgres:alpine
Pulling pgadmin (dpage/pgadmin4:)...
Status: Downloaded newer image for dpage/pgadmin4:latest
Creating rhumapp_pgsql_db ... 
Creating rhumapp_pgadmin  ... 
Creating rhumapp_nodejs_api ... 
Creating rhumapp_balancer   ... 
$ docker-compose exec -T app sequelize db:migrate
Sequelize CLI [Node: 14.12.0, CLI: 6.2.0, ORM: 5.22.3]
Loaded configuration file "App/database/config/config.js".
Using environment "development".
== 20200510143520-create-roles: migrating =======
== 20200510143520-create-roles: migrated (0.077s)
== 20200510143537-create-pathologies: migrating =======
== 20200510143537-create-pathologies: migrated (0.023s)
== 20200510143550-create-users: migrating =======
== 20200510143550-create-users: migrated (0.042s)
== 20200912152142-create-logger: migrating =======
== 20200912152142-create-logger: migrated (0.055s)
== 20201003110408-create-articulations: migrating =======
== 20201003110408-create-articulations: migrated (0.047s)
== 20201003112546-create-user-articulations: migrating =======
== 20201003112546-create-user-articulations: migrated (0.049s)
$ docker-compose exec -T app sequelize db:seed:all
Sequelize CLI [Node: 14.12.0, CLI: 6.2.0, ORM: 5.22.3]
Loaded configuration file "App/database/config/config.js".
Using environment "development".
== 20200510143520-Roles: migrating =======
== 20200510143520-Roles: migrated (0.049s)
== 20200510143537-Pathologies: migrating =======
== 20200510143537-Pathologies: migrated (0.008s)
== 20200510143550-User: migrating =======
== 20200510143550-User: migrated (0.045s)
== 20201003110923-Articulations: migrating =======
== 20201003110923-Articulations: migrated (0.018s)
$ docker-compose exec -T app npm test
> Rhumapp@1.0.0 test /app
> mocha tests --reporter mocha-junit-reporter --reporter-options mochaFile=./test_results/test-results.xml --unhandled-rejections=strict
npm ERR! Test failed.  See above for more details.
Running after_script
Running after script...
$ docker-compose stop
Stopping rhumapp_balancer   ... 
Stopping rhumapp_nodejs_api ... 
Stopping rhumapp_pgadmin    ... 
Stopping rhumapp_pgsql_db   ... 
Uploading artifacts for failed job
Uploading artifacts...
test_results/test-results.xml: found 1 matching files and directories 
Uploading artifacts as "archive" to coordinator... ok  id=773097939 responseStatus=201
Uploading artifacts...
test_results/test-results.xml: found 1 matching files and directories 
Uploading artifacts as "junit" to coordinator... ok  id=773097939 responseStatus=201
Cleaning up file based variables
ERROR: Job failed: exit code 1
```

**Comment by austince** [comment]
Do you have your docker-compose file as well? :grimacing:

**Comment by cmattern68** [comment]
Yep, the server is running in the app container ! Here is the docker infos:

```yml
version: '3'
services:
  nginx:
    container_name: rhumapp_balancer
    build: ./nginx
    links:
      - app:app
      - pgadmin:pgadmin
    ports:
      - "80:80"
  app:
    image: rhumappbackend
    container_name: rhumapp_nodejs_api
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://:@postgres:5432/
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules
      - ./test_results:/tests
    restart: unless-stopped

  postgres:
    container_name: rhumapp_pgsql_db
    image: postgres:alpine
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "35432:5432"
    restart: unless-stopped

  pgadmin:
    hostname: pgadmin
    container_name: rhumapp_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

volumes:
    postgres:
    pgadmin:
```

Dockerfile:
```Dockerfile
FROM node

WORKDIR /app

COPY ./package.json .
COPY ./package-lock.json .

RUN npm install -g nodemon
RUN npm install

COPY . .

RUN npm install -g --save sequelize-cli
RUN npm install -g mocha-junit-reporter

COPY ./PostgreSQL/docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
```

nginx.conf
```nginxconf
user  nginx;
worker_processes auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events { worker_connections 1024; }

http {

  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"';

  access_log  /dev/null;

  upstream app {
    least_conn;
    server app:3000 weight=10 max_fails=3 fail_timeout=30s;
  }

  sendfile        on;
  #tcp_nopush     on;

  keepalive_timeout  65;

  #gzip  on;

  server {
    listen 80;

    location /api/ {
      proxy_pass http://app;
        proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location / {
      proxy_pass http://pgadmin;
        proxy_http_version 1.1;
      proxy_set_header X-Script-Name /pgadmin;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
```
